### ISSUE TITLE
Can we compile pygame for Android 2.3.3?

### ISSUE THREAD

**Issue by martinho23** [renpytom/rapt-pygame-example#2]
Can we change the version of android that we compile for?
for exemple if i don't want to compile my apk for Android 4.4 but insted i want to compile to Android 2.3 what i have to change??

PS: Sorry for bad English

**Comment by renpytom** [comment]
It probably should work if you answer the question correctly in the configure step. It'll ask what the version you want to target is. I haven't tested on 2.3 in a long time, since it's been obsolete forever.

**Comment by martinho23** [comment]
I wanted to try on 2.3 becose my phone it kind a old and its and its more simple to use your phone to test instead emulators. i just wanted to know what i have to change to compile on 2.3.

**Comment by Tetopia** [comment]
I'm interested in this question too. I too have an Android 2.3 phone and want to get my pygame running on that phone. It does work on Android 7.0 just fine but on Android 2.3 it crashes with this Error:

BUILD SUCCESSFUL
Total time: 1 minute 4 seconds

Launching app.

Starting: Intent { act=android.intent.action.MAIN dat=org.renpy.android_test/org
.renpy.android.PythonSDLActivity }
Error: Activity not started, unable to resolve Intent { act=android.intent.actio
n.MAIN dat=org.renpy.android_test/org.renpy.android.PythonSDLActivity flg=0x1000
0000 }

The build seems to have succeeded.


In the android.py configuration I chose Android 2.2, so that shouldn't be a problem. I got both the API 8 and API 10 next to the API 22 in the android-sdk-r24.4.1/plattforms
I guess it simply builds with a target API 22...
There is the `target=android-22` in the project.properties and it seems I can't get it to 8 or 10.
Do you have any idea how I could get it going on my phone?

Besides this problem it's just great to be able to get pygames running on Android! Thanks :-)
